CREATE TABLE IF NOT EXISTS message (
    id SERIAL PRIMARY KEY,
    chatId VARCHAR(100) NOT NULL,
    fromUserId VARCHAR(100) NOT NULL,
    toUserId VARCHAR(100) NOT NULL,
    body TEXT NOT NULL,
    sentDate TIMESTAMP NOT NULL,
    receivedDate TIMESTAMP,
    isRead BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
